services:
  rabbitmq1:
    image: rabbitmq:4-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie_value_change_me"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
      - ./cluster.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - rabbitmq_network
    restart: unless-stopped

  rabbitmq2:
    image: rabbitmq:4-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie_value_change_me"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
      - ./cluster.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - rabbitmq_network
    restart: unless-stopped
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:4-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie_value_change_me"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
      - ./cluster.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - rabbitmq_network
    restart: unless-stopped
    depends_on:
      - rabbitmq1

  amqproxy:
    image: cloudamqp/amqproxy:latest
    container_name: amqproxy
    ports:
      - "5675:5675"
      - "8080:8080"
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq1:5672"
      LISTEN_PORT: 5675
      CONNECTION_POOL_SIZE: 10
      MAX_CHANNELS_PER_CONNECTION: 100
      METRICS_PORT: 8080
    networks:
      - rabbitmq_network
    restart: unless-stopped
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data: